### PR TITLE
Actually enforce auth

### PR DESCRIPTION
**Pull request by Singletoned**

### CODE REVIEW

**Review by rottitime — CHANGES_REQUESTED** [review]
@Singletoned Can we have some endpoints public please like list of grades, skills, contract types?

There is a genuine reason for this as I use optimisation. The data here is prefetched which means I don't need preloaders. Pages also load much faster.

If you are happy for this I can give you a list of endpoints. If not then I will go ahead and add auth as we discussed

**Comment by Singletoned** [comment]
Yeah, that's fine.  As long as they are generic data, it should be fine

**Comment by Singletoned** [comment]
Currently, the ones I've made public are:
```
organisations
contract-types
locations
languages
professions
grades
language-skill-levels
countries
functions
skill-levels
skills
```

**Comment by rottitime** [comment]
> Currently, the ones I've made public are:
> 
> ```
> organisations
> contract-types
> locations
> languages
> professions
> grades
> language-skill-levels
> countries
> functions
> skill-levels
> skills
> ```

@Singletoned  Yes, this list matches what I have in the code

**Review by rottitime — APPROVED** [review]

**Comment by rottitime** [comment]
@Singletoned  All good. Just did a test against the PR: https://github.com/i-dot-ai/ellandi/pull/316
Looks like we are successfully passing and reading the session token

**Pull request merged**
