### PR TITLE
Add standalone app deployment

### PR DESCRIPTION
**Pull request by rickyp72**
Intermediate step with all ellandi apps being deployed.  NEXT_PUBLIC_API_URL is being set in deploy.yml for all apps

### CODE REVIEW

**Comment by Singletoned** [comment]
This doesn't look right at all.  Your commit has way too much stuff in it: https://github.com/i-dot-ai/ellandi/pull/494/commits/eb3d13a4f2d2a8ff339183f4531c8f08663782c1

**Comment by Singletoned** [comment]
There should only really be some changes to the GitHub actions and some new manifests

**Comment by rickyp72** [comment]
@Singletoned I had to separated create an ellandi/ app folder from api/ so there wasn't conflicting HOST_MAP entries thought this would be cleaner then we can just remove api/ when ready. It also has its own docker files etc..

**Comment by Singletoned** [comment]
Duplicating almost 100 files is never a good idea, particularly when those files are being actively developed

**Comment by rickyp72** [comment]
Sure - i'm trying now to get it working with the single set of files

**Pull request closed without merging**
