### PR TITLE
Feature/self reported lm

### PR DESCRIPTION
**Pull request by nmenezes0**
Adds a "self-reported" line manager field to the backend. @aialopes - this adds `is_self_reported_line_manager` to the API (with options "Yes", "No", "I don't know") - the existing field `is_line_manager` is autocalculated based on if that user has been recorded as a line manager by someone else.

As part of this Trello ticket: https://trello.com/c/TqJ1DPMY/168-add-line-manager-question-to-sign-up-and-profile

### CODE REVIEW

**Comment by Singletoned** [comment]
I don't like that `is_mentor` and `is_self_reported_line_manager` are both self-reported, but `is_line_manager` isn't.  I think we need to rethink the names a little.  Given that almost everything in the system is self-reported, I think we should go with something like `is_mentor`, `is_line_manager`, and `is_accused_of_being_a_line_manager_by_someone_else`

**Comment by nmenezes0** [comment]
> I don't like that `is_mentor` and `is_self_reported_line_manager` are both self-reported, but `is_line_manager` isn't. I think we need to rethink the names a little. Given that almost everything in the system is self-reported, I think we should go with something like `is_mentor`, `is_line_manager`, and `is_accused_of_being_a_line_manager_by_someone_else`

That is a great field name, let's go with that ;-)

But I know what you mean.... 
`derived_line_manager` or even `has_direct_reports`?

**Comment by Singletoned** [comment]
`has_direct_reports` is perfect!

**Comment by nmenezes0** [comment]
Field names now changed.

What was `is_line_manager` is now `has_direct_reports` (autocalculated) and there is a new field `is_line_manager` which can be completed by the user ("Yes", "No", "I don't know").

**Comment by Singletoned** [comment]
Redo the migrations as a single migration, and then this looks great.  Don't merge it until one of @rottitime or @aialopes has approved the frontend stuff.

**Review by Singletoned — APPROVED** [review]

**Review by aialopes — APPROVED** [review]

**Pull request merged**
