### PR TITLE
Feature/reporting overview

### LINKED ISSUE #715: API Report:  Staff overview
Ticket: https://trello.com/c/dUpaUKPF/233-reports-staff-overview-tab

# Responsibility
Endpoint: 'GET /me/reports/responsibility/'

Response
```
{
    data: [
        {
            name: string //e.g. Line managers
            total_label: string //e.g. 350 (36%)
            total_value_total: number //e.g. 350
            total_value_percentage: number //e.g. 36
        }
    ]
}
```

# Grade
Endpoint: 'GET /me/reports/grade/'

Response
```
{
    data: [
        {
  name: string //e.g. Administrative Officer (AO) Equivalent
  total_label: string //e.g. 350 (36%)
  total_value_total: number //e.g. 350
  total_value_percentage: number //e.g. 36
        }
    ]
}
```

# Format

Endpoint supports following query-string values

```
format=csv // eg. csv, excel, pdf
```

### PR DESCRIPTION
**Pull request by nmenezes0**
Fixes #715 .

Need to rebase once `feature/reporting` has been merged into `develop` (then this PR will be much simpler).

Have also added `staff-overview` endpoint (just for CSV download) as discussed below (no need to pass in `format=csv` as is just CSV).

### CODE REVIEW

**Review by rottitime — CHANGES_REQUESTED** [review]
.

**Review by rottitime — CHANGES_REQUESTED** [review]
@nmenezes0 Could you also return `total_label` in the below please. This is what gets printed out on the UI. Thanks

`/me/reports/responsibilities/`
```
data:  [
...
{name: "Total users", total_value_total: 2}
]
```

**Comment by nmenezes0** [comment]
> @nmenezes0 Could you also return `total_label` in the below please. This is what gets printed out on the UI. Thanks
> 
> `/me/reports/responsibilities/`
> 
> ```
> data:  [
> ...
> {name: "Total users", total_value_total: 2}
> ]
> ```

For consistency, should `total_label` be e.g. `2 (100%)` i.e. formatted number and percentage?
Or should it just be the total number of users i.e. `2`?

**Comment by rottitime** [comment]
> For consistency, should `total_label` be e.g. `2 (100%)` i.e. formatted number and percentage? Or should it just be the total number of users i.e. `2`?

@nmenezes0 `label` will always be the screen friendly version that gets shown on the page. The other values (e.g. `total_percentage`) I use in background for sorting and other logic. 

In this case it will be total number (e.g. 2). Thanks

Screenshot 2022-11-07 at 21 05 24

**Comment by nmenezes0** [comment]
> 

That change is now pushed

**Comment by nmenezes0** [comment]
@rottitime - at the moment there are two endpoints for the responsibilities and grades. Will there be two CSV exports or just one with all the data? If just one, then might need a different endpoint for the CSV download.

**Comment by rottitime** [comment]
> @rottitime - at the moment there are two endpoints for the responsibilities and grades. Will there be two CSV exports or just one with all the data? If just one, then might need a different endpoint for the CSV download.

@nmenezes0 they have given the following AC: "_If 'Export' is selected, export all staff data (both responsibility and grade breakdowns)_". I can change the endpoint for this button. What API were you thinking to use?

**Comment by nmenezes0** [comment]
> > @rottitime - at the moment there are two endpoints for the responsibilities and grades. Will there be two CSV exports or just one with all the data? If just one, then might need a different endpoint for the CSV download.
> 
> @nmenezes0 they have given the following AC: "_If 'Export' is selected, export all staff data (both responsibility and grade breakdowns)_". I think one url would work best. I can change the endpoint for this button. What API were you thinking to use?

Sure - I'll create another endpoint that aggregates data for CSV download (maybe just CSV format for this one, or should I have JSON as well?). Maybe something like `/reports/staffoverview/`?

**Review by rottitime — APPROVED** [review]
From UI point of view this ticks all the boxes!

**Comment by nmenezes0** [comment]
> > > @rottitime - at the moment there are two endpoints for the responsibilities and grades. Will there be two CSV exports or just one with all the data? If just one, then might need a different endpoint for the CSV download.
> > 
> > 
> > @nmenezes0 they have given the following AC: "_If 'Export' is selected, export all staff data (both responsibility and grade breakdowns)_". I think one url would work best. I can change the endpoint for this button. What API were you thinking to use?
> 
> Sure - I'll create another endpoint that aggregates data for CSV download (maybe just CSV format for this one, or should I have JSON as well?). Maybe something like `/reports/staffoverview/`?

@rottitime - have actually now added this new endpoint but is called `/reports/staff-overview/` and only returns the CSV.

**Comment by rottitime** [comment]
> have actually now added this new endpoint but is called `/reports/staff-overview/` and only returns the CSV

Will update the code. Is the full url: `/me/reports/staff-overview/` with no query strings?

**Review by Singletoned — APPROVED** [review]

**Comment by nmenezes0** [comment]
> > have actually now added this new endpoint but is called `/reports/staff-overview/` and only returns the CSV
> 
> Will update the code. Is the full url: `/me/reports/staff-overview/` with no query strings?

Yup - that's right @rottitime - no query strings, just `/me/reports/staff-overview/`.

**Pull request merged**
