### PR TITLE
Add Github scheduling test

### PR DESCRIPTION
**Pull request by rickyp72**
this test will start a stop Cloudfoundry app to run the cron task and then kill it

### CODE REVIEW

**Comment by Singletoned** [comment]
You need to rebase this on top of `develop` and you need to stop merging `develop` into branches

**Review by Singletoned — CHANGES_REQUESTED** [review]
Rebase, don't merge

**Comment by rickyp72** [comment]
Ah.. the merge is what github does when you click the button to fix PR thats gone out of sync with develop. Ok. ill stop using that.

**Comment by Singletoned** [comment]
There should be an option next to that button to do a rebase instead of a merge.  But otherwise just do:
```
git pull origin develop --rebase
git push feature/mybranch --force-with-lease
```

**Pull request closed without merging**
