### PR TITLE
Nginx CORS headers

### PR DESCRIPTION
**Pull request by rickyp72**
Remove Django CORS module and add Nginx headers

### CODE REVIEW

**Review by rottitime — CHANGES_REQUESTED** [review]
@rickyp72 I appear to get the following errors

```
Access to fetch at 'http://localhost/api/login/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I run the new commands Ed has given:;

```
docker compose up nginx api

**Review by rottitime — APPROVED** [review]
@rickyp72 I can confirm that localhost works with your latest updates. Not sure if you need to get Ed to check the code though

**Comment by Singletoned** [comment]
Let me have a think about this.  I'm still deciding which is the lesser of two evils

**Comment by rickyp72** [comment]
Just added the testing label again so it doesn't get merge until @Singletoned has decided.

**Pull request closed without merging**
