### PR TITLE
Exposes env vars / git SHA info

### PR DESCRIPTION
**Pull request by aialopes**
Closes https://trello.com/c/9aXxfVkC/178-debug-page

image

### CODE REVIEW

**Review by rottitime — DISMISSED** [review]
@aialopes Really good choice to use json here. 

I know we have `apiUrl`. Do we need to also just add the `NEXT_PUBLIC_API_URL` to make it clear?

**Comment by aialopes** [comment]
> @aialopes Really good choice to use json here.
> 
> I know we have `apiUrl`. Do we need to also just add the `NEXT_PUBLIC_API_URL` to make it clear?

@rottitime, `apiUrl` is `NEXT_PUBLIC_API_URL` right?

**Comment by Singletoned** [comment]
Nice one!  Looks great.  Can we label the url as `NEXT_PUBLIC_API_URL` to make it clear for us backend devs?

**Comment by rottitime** [comment]
> @aialopes Really good choice to use json here.
> 
> I know we have `apiUrl`. Do we need to also just add the `NEXT_PUBLIC_API_URL` to make it clear?

@aialopes can we have both? `NEXT_PUBLIC_API_URL` even if you have to manually code it. Will be good for BE devs

**Review by rickyp72 — DISMISSED** [review]

**Review by rottitime — APPROVED** [review]

**Comment by rottitime** [comment]
@aialopes looks good

**Pull request merged**
