### PR TITLE
Feature/learning sort

### LINKED ISSUE #573: API: Sort for Learning
Can you update the `GET /me/learnings/` endpoint to accept optional query parameters for sorting

#### Optional Params
sortfield: name of the field in the object e.g. `name`, `duration_minutes `
sortorder (defaults: asc): accepts `asc` or `desc`. 

#### Example
```lang-js
/me/learnings/?sortfield=name&sortorder=asc
```

### PR DESCRIPTION
**Pull request by nmenezes0**
Fixes #573.

@rottitime - you can now pass in `sortfield` however I didn't add `sortorder=asc` as you can just pass in `-` before the fieldname to get descending (it's ascending by default). For example, `/me/learnings/?sortfield=-name` would sort descending.

### CODE REVIEW

**Comment by Singletoned** [comment]
The names we expose on the api don't particularly need to reflect the names that Django uses, and I'm not convinced that `sortfield` is the best name for this.

**Comment by nmenezes0** [comment]
> The names we expose on the api don't particularly need to reflect the names that Django uses, and I'm not convinced that `sortfield` is the best name for this.

Any advances on a better name? 
- `order_by` (or `orderby`)?
- `sort_by`?

**Review by Singletoned — APPROVED** [review]

**Comment by Singletoned** [comment]
It's up to @rottitime .  If he's happy with it, it's fine

**Comment by nmenezes0** [comment]
> It's up to @rottitime . If he's happy with it, it's fine

In which case, I'll assume it's ok!

**Pull request merged**
