### PR TITLE
Feature/pending

### PR DESCRIPTION
**Pull request by nmenezes0**
Adds a field "pending" to the `UserSkill` model.

Can now update this `pending` field on the `/api/me/skills/` endpoint.

Can also get all pending skills for a given user  `GET /api/me/skills/?pending=true`.

Completes #669 (assuming we don't need to do the line manager review bit).

### CODE REVIEW

**Comment by nmenezes0** [comment]
@rottitime - for info

**Comment by rottitime** [comment]
@nmenezes0 does this set `pending:true` for any scenarios?

**Comment by nmenezes0** [comment]
> @nmenezes0 does this set `pending:true` for any scenarios?

At the moment it defaults to false, and you have to explicitly set it to true. (Don't know if that's the right way to do things.)

I think when a person is adding a brand new skill (i.e. not adding a skill from the existing skills endpoint), that's when you would set it to be true.

**Comment by rottitime** [comment]
> I think when a person is adding a brand new skill (i.e. not adding a skill from the existing skills endpoint), that's when you would set it to be true.

Would it be possible to have this feature? or will this be setup in a later PR?

**Comment by nmenezes0** [comment]
> > I think when a person is adding a brand new skill (i.e. not adding a skill from the existing skills endpoint), that's when you would set it to be true.
> 
> Would it be possible to have this feature? or will this be setup in a later PR?

So, when adding a new skill then automatically determine if pending = True?

I think that is possible yes. Give that we're going to be refactoring the pending skills stuff anyway (as we were discussing in the meeting this morning), then that will be in a separate PR.

**Comment by nmenezes0** [comment]
@Singletoned - I've added the `pending` field to the "skills to develop" model. I'm having loads of trouble with it, for some reason `PATCH` to that endpoint is failing.

Please can you have a look - have a missed something obvious?

**Comment by nmenezes0** [comment]
@Singletoned - have commented out test as we discussed, now ready for review (and merge if you're happy with it).

**Pull request merged**
